name: davidlkmurphy
favicon: null
layout_spectrum: 0.3458288081455976
typography_spectrum: 0.48128113988786936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4795633826870471
  lightness: 0.010236546862870455
  saturation: 0.9456946684513241
  rhythmicContrast: 0.6687523967120796
purpose: []
